//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarDetailingStudio.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class additionalTireStorageServices
    {
        public int IdAdditionalTireStorageServices { get; set; }
        public int clientsOfCarWashId { get; set; }
        public int orderServicesCarWashId { get; set; }
        public int tireStorageServicesd { get; set; }
        public double Price { get; set; }
    
        public virtual OrderServicesCarWash OrderServicesCarWash { get; set; }
        public virtual TireStorageServices TireStorageServices { get; set; }
    }
}
