//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarDetailingStudio.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class carWashEntities : DbContext
    {
        public carWashEntities()
            : base("name=carWashEntities")
        {
            Configuration.LazyLoadingEnabled = false;
            Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<additionalTireStorageServices> additionalTireStorageServices { get; set; }
        public virtual DbSet<bonusToSalary> bonusToSalary { get; set; }
        public virtual DbSet<brigadeForToday> brigadeForToday { get; set; }
        public virtual DbSet<car_generation> car_generation { get; set; }
        public virtual DbSet<car_mark> car_mark { get; set; }
        public virtual DbSet<car_model> car_model { get; set; }
        public virtual DbSet<car_modification> car_modification { get; set; }
        public virtual DbSet<car_serie> car_serie { get; set; }
        public virtual DbSet<CarBody> CarBody { get; set; }
        public virtual DbSet<CarWashWorkers> CarWashWorkers { get; set; }
        public virtual DbSet<Cashier> Cashier { get; set; }
        public virtual DbSet<ClientInfo> ClientInfo { get; set; }
        public virtual DbSet<ClientsGroups> ClientsGroups { get; set; }
        public virtual DbSet<ClientsOfCarWash> ClientsOfCarWash { get; set; }
        public virtual DbSet<costCategories> costCategories { get; set; }
        public virtual DbSet<Credit> Credit { get; set; }
        public virtual DbSet<Detailings> Detailings { get; set; }
        public virtual DbSet<ExchangeRates> ExchangeRates { get; set; }
        public virtual DbSet<expenseCategory> expenseCategory { get; set; }
        public virtual DbSet<Expenses> Expenses { get; set; }
        public virtual DbSet<GroupWashServices> GroupWashServices { get; set; }
        public virtual DbSet<JobTitleTable> JobTitleTable { get; set; }
        public virtual DbSet<orderCarpetWashing> orderCarpetWashing { get; set; }
        public virtual DbSet<OrderCarWashWorkers> OrderCarWashWorkers { get; set; }
        public virtual DbSet<OrderServicesCarWash> OrderServicesCarWash { get; set; }
        public virtual DbSet<PaymentState> PaymentState { get; set; }
        public virtual DbSet<PriceListTireFitting> PriceListTireFitting { get; set; }
        public virtual DbSet<PriceListTireFittingAdditionalServices> PriceListTireFittingAdditionalServices { get; set; }
        public virtual DbSet<salaryBalance> salaryBalance { get; set; }
        public virtual DbSet<salaryExpenses> salaryExpenses { get; set; }
        public virtual DbSet<ServisesCarWashOrder> ServisesCarWashOrder { get; set; }
        public virtual DbSet<StatusOrder> StatusOrder { get; set; }
        public virtual DbSet<storageFee> storageFee { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tireChangeService> tireChangeService { get; set; }
        public virtual DbSet<TireRadius> TireRadius { get; set; }
        public virtual DbSet<tireService> tireService { get; set; }
        public virtual DbSet<TireStorage> TireStorage { get; set; }
        public virtual DbSet<TireStorageServices> TireStorageServices { get; set; }
        public virtual DbSet<TypeOfCars> TypeOfCars { get; set; }
        public virtual DbSet<typeOfOrder> typeOfOrder { get; set; }
        public virtual DbSet<utilityCosts> utilityCosts { get; set; }
        public virtual DbSet<utilityCostsCategory> utilityCostsCategory { get; set; }
        public virtual DbSet<logo_mark_car> logo_mark_car { get; set; }
        public virtual DbSet<infoBrigadeForToday> infoBrigadeForToday { get; set; }
        public virtual DbSet<ItogOrderView> ItogOrderView { get; set; }
        public virtual DbSet<AdditionalIncome> AdditionalIncome { get; set; }
        public virtual DbSet<goodsSold> goodsSold { get; set; }
        public virtual DbSet<listOfGoods> listOfGoods { get; set; }
        public virtual DbSet<procurement> procurement { get; set; }
        public virtual DbSet<ProductCategories> ProductCategories { get; set; }
    }
}
