//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarDetailingStudio.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cashier
    {
        public int idCashier { get; set; }
        public System.DateTime date { get; set; }
        public double amountBeginningOfTheDay { get; set; }
        public double amountEndOfTheDay { get; set; }
    }
}
