//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarDetailingStudio.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Credit
    {
        public int Id { get; set; }
        public Nullable<int> CarWashWorkersId { get; set; }
        public Nullable<System.DateTime> loanDate { get; set; }
        public Nullable<double> IssueAmount { get; set; }
        public Nullable<double> RepaymentAmount { get; set; }
        public Nullable<double> SalaryPercentage { get; set; }
        public Nullable<System.DateTime> maturityDate { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual CarWashWorkers CarWashWorkers { get; set; }
    }
}
