//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarDetailingStudio.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeRate
    {
        public int idEmployeeRate { get; set; }
        public Nullable<int> brigadeForTodayId { get; set; }
        public Nullable<int> numberHoursWorked { get; set; }
        public Nullable<double> hourlyRate { get; set; }
        public Nullable<double> wage { get; set; }
    
        public virtual brigadeForToday brigadeForToday { get; set; }
    }
}
