//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarDetailingStudio.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExchangeRates
    {
        public int Id { get; set; }
        public string ccy { get; set; }
        public string base_ccy { get; set; }
        public Nullable<double> buy { get; set; }
        public Nullable<double> sale { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
