//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarDetailingStudio.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expenses
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Expenses()
        {
            this.salaryExpenses = new HashSet<salaryExpenses>();
            this.utilityCosts = new HashSet<utilityCosts>();
            this.procurement = new HashSet<procurement>();
        }
    
        public int idExpenses { get; set; }
        public int expenseCategoryId { get; set; }
        public Nullable<System.DateTime> dateExpenses { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<int> paymentType { get; set; }
        public string note { get; set; }
        public Nullable<int> idCostCategories { get; set; }
    
        public virtual expenseCategory expenseCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<salaryExpenses> salaryExpenses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<utilityCosts> utilityCosts { get; set; }
        public virtual costCategories costCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<procurement> procurement { get; set; }
    }
}
