//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarDetailingStudio.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class goodsSold
    {
        public int idGoodsSold { get; set; }
        public Nullable<int> listOfGoodsId { get; set; }
        public Nullable<int> carWashWorkersId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<double> priceForOne { get; set; }
        public Nullable<double> amount { get; set; }
        public Nullable<double> orderPrice { get; set; }
        public Nullable<double> percentageOfSale { get; set; }
        public Nullable<int> PaymentState { get; set; }
    
        public virtual listOfGoods listOfGoods { get; set; }
    }
}
