//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarDetailingStudio.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class listOfGoods
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public listOfGoods()
        {
            this.goodsSold = new HashSet<goodsSold>();
            this.procurement = new HashSet<procurement>();
        }
    
        public int idListOfGoods { get; set; }
        public Nullable<int> productCategoriesId { get; set; }
        public string name { get; set; }
        public string productDescription { get; set; }
        public string urlFoto { get; set; }
        public Nullable<bool> visible { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<double> salaryFromSale { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<goodsSold> goodsSold { get; set; }
        public virtual ProductCategories ProductCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<procurement> procurement { get; set; }
    }
}
