//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarDetailingStudio.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class premiumAndRate
    {
        public int idPremiumAndRate { get; set; }
        public int carWashWorkersId { get; set; }
        public bool positionsStatus { get; set; }
        public Nullable<double> percentageRatePerOrder { get; set; }
        public int positionId { get; set; }
        public bool servicePremium { get; set; }
        public Nullable<double> multiplicityOfTheSum { get; set; }
        public Nullable<double> prizeAmount { get; set; }
    
        public virtual CarWashWorkers CarWashWorkers { get; set; }
        public virtual Position Position { get; set; }
    }
}
