//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarDetailingStudio.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceListTireFitting
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PriceListTireFitting()
        {
            this.tireChangeService = new HashSet<tireChangeService>();
        }
    
        public int idPriceListTireFitting { get; set; }
        public string JobTitle { get; set; }
        public Nullable<int> TheCost { get; set; }
        public Nullable<int> TireRadiusId { get; set; }
        public Nullable<double> TypeOfCarsId { get; set; }
    
        public virtual TireRadius TireRadius { get; set; }
        public virtual TypeOfCars TypeOfCars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tireChangeService> tireChangeService { get; set; }
    }
}
