//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarDetailingStudio.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class procurement
    {
        public int idProcurement { get; set; }
        public Nullable<int> ListOfGoodsId { get; set; }
        public Nullable<int> expensesId { get; set; }
        public Nullable<int> amount { get; set; }
        public Nullable<int> remainder { get; set; }
    
        public virtual Expenses Expenses { get; set; }
        public virtual listOfGoods listOfGoods { get; set; }
    }
}
