//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarDetailingStudio.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseCosts
    {
        public int Id { get; set; }
        public Nullable<int> IdRetail { get; set; }
        public Nullable<int> IdCosts { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Amount { get; set; }
    
        public virtual Costs Costs { get; set; }
        public virtual Retail Retail { get; set; }
    }
}
