//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarDetailingStudio.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class salaryBalance
    {
        public int idSalaryBalance { get; set; }
        public Nullable<int> CarWashWorkersId { get; set; }
        public Nullable<System.DateTime> dateOfPayment { get; set; }
        public Nullable<double> payoutAmount { get; set; }
        public Nullable<double> accountBalance { get; set; }
        public bool currentMonthStatus { get; set; }
    
        public virtual CarWashWorkers CarWashWorkers { get; set; }
    }
}
