//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarDetailingStudio.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class salaryArchive
    {
        public int idSalaryArchive { get; set; }
        public int carWashWorkersId { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> amountOfCompletedOrders { get; set; }
        public Nullable<double> monthlySalaryAmountEarned { get; set; }
        public Nullable<double> monthlySalaryAmountReceived { get; set; }
        public Nullable<double> balanceAtTheEndOfTheMonth { get; set; }
        public Nullable<bool> salaryStatus { get; set; }
    
        public virtual CarWashWorkers CarWashWorkers { get; set; }
    }
}
