//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarDetailingStudio.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class storageFee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public storageFee()
        {
            this.TireStorage = new HashSet<TireStorage>();
        }
    
        public int idStorageFee { get; set; }
        public Nullable<System.DateTime> DateOfPayment { get; set; }
        public Nullable<double> amount { get; set; }
        public Nullable<int> storageTime { get; set; }
        public Nullable<bool> storageStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TireStorage> TireStorage { get; set; }
    }
}
