//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarDetailingStudio.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tireChangeService
    {
        public int idTireChangeService { get; set; }
        public int idOrder { get; set; }
        public int priceListTireFittingId { get; set; }
        public Nullable<int> numberOfTires { get; set; }
        public Nullable<int> tireRadius { get; set; }
        public Nullable<double> price { get; set; }
    
        public virtual OrderServicesCarWash OrderServicesCarWash { get; set; }
        public virtual PriceListTireFitting PriceListTireFitting { get; set; }
    }
}
