//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarDetailingStudio.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TireStorageServices
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TireStorageServices()
        {
            this.additionalTireStorageServices = new HashSet<additionalTireStorageServices>();
        }
    
        public int Id { get; set; }
        public string ServicesName { get; set; }
        public Nullable<int> radius { get; set; }
        public Nullable<int> amount { get; set; }
        public Nullable<int> storageTime { get; set; }
        public Nullable<double> Price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<additionalTireStorageServices> additionalTireStorageServices { get; set; }
    }
}
