//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarDetailingStudio.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class utilityCosts
    {
        public int idUtilityCosts { get; set; }
        public Nullable<int> indicationCounter { get; set; }
        public Nullable<int> utilityCostsCategoryId { get; set; }
        public Nullable<int> expenseId { get; set; }
    
        public virtual Expenses Expenses { get; set; }
        public virtual utilityCostsCategory utilityCostsCategory { get; set; }
    }
}
