//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarDetailingStudio.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewClientsOfCarWash
    {
        public int ib { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string PatronymicName { get; set; }
        public string phone { get; set; }
        public Nullable<System.DateTime> DateRegistration { get; set; }
        public string Email { get; set; }
        public string discont { get; set; }
        public string Recommendation { get; set; }
        public string NumderCar { get; set; }
        public string Mark { get; set; }
        public string Model { get; set; }
        public string Body { get; set; }
        public string note { get; set; }
        public string barcode { get; set; }
        public string Groups { get; set; }
    }
}
