//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarDetailingStudio.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wage
    {
        public int Id { get; set; }
        public int IdCarWashWorkers { get; set; }
        public int CostsId { get; set; }
    
        public virtual CarWashWorkers CarWashWorkers { get; set; }
        public virtual Costs Costs { get; set; }
    }
}
