//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarDetailingStudio.DataBase.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class logo_mark_car
    {
        public double id_car_mark { get; set; }
        public byte[] logo_mark { get; set; }
        public string screen_format { get; set; }
    }
}
