//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarDetailingStudio.DataBase.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderServicesCarWash
    {
        public int Id { get; set; }
        public Nullable<int> IdClientsOfCarWash { get; set; }
        public int IdServisesCarWashOrder { get; set; }
        public Nullable<int> idCarWashWorkers { get; set; }
        public string discount { get; set; }
        public string StatusOrder { get; set; }
        public string PaymentState { get; set; }
        public string OrderDate { get; set; }
        public string ExecutionTime { get; set; }
        public string ClosingData { get; set; }
        public string ClosingTime { get; set; }
        public Nullable<double> TotalCostOfAllServices { get; set; }
    
        public virtual brigadeForToday brigadeForToday { get; set; }
        public virtual ClientsOfCarWash ClientsOfCarWash { get; set; }
        public virtual ServisesCarWashOrder ServisesCarWashOrder { get; set; }
    }
}
